<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Event;
use App\Models\Category;
use App\Models\Instructor;
use Illuminate\Support\Str;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get categories
        $eventCategories = Category::where('type', 'event')->get();
        $courseCategories = Category::where('type', 'course')->get();
        $instructors = Instructor::all();

        // Get admin user
        $adminId = \App\Models\User::where('role', 'admin')->first()->id ?? 1;

        // Events Data (15 events)
        $events = [
            [
                'title' => 'African Startup Summit 2025',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Business & Entrepreneurship')->first()->id,
                'short_description' => 'Join Africa\'s leading entrepreneurs for a day of networking and inspiration',
                'description' => 'The African Startup Summit brings together the continent\'s most innovative entrepreneurs, investors, and thought leaders for a full day of keynotes, panel discussions, and networking opportunities. Learn from successful founders, connect with potential investors, and discover the latest trends in African entrepreneurship.',
                'location' => 'Rainbow Towers, Harare',
                'location_type' => 'physical',
                'start_date' => now()->addDays(30),
                'start_time' => '09:00',
                'end_time' => '17:00',
                'capacity' => 500,
                'amount' => 50,
                'currency' => 'USD',
                'duration_hours' => 8,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Tech Innovation Conference',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Technology & Innovation')->first()->id,
                'short_description' => 'Explore the future of technology and digital transformation',
                'description' => 'A comprehensive conference featuring the latest in AI, blockchain, cloud computing, and digital transformation. Hear from tech leaders, participate in hands-on workshops, and network with fellow technologists.',
                'location' => 'Virtual Event',
                'location_type' => 'online',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(45),
                'start_time' => '10:00',
                'end_time' => '16:00',
                'capacity' => 1000,
                'amount' => 30,
                'currency' => 'USD',
                'duration_hours' => 6,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Digital Marketing Masterclass',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Marketing & Sales')->first()->id,
                'short_description' => 'Master the art of digital marketing in one intensive day',
                'description' => 'Learn proven strategies for social media marketing, content creation, SEO, and paid advertising. This hands-on masterclass will give you the tools and techniques to grow your online presence.',
                'location' => 'Meikles Hotel, Harare',
                'location_type' => 'hybrid',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(20),
                'start_time' => '08:30',
                'end_time' => '17:30',
                'capacity' => 200,
                'amount' => 75,
                'currency' => 'USD',
                'duration_hours' => 9,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Leadership Excellence Forum',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Leadership & Management')->first()->id,
                'short_description' => 'Develop exceptional leadership skills for the modern workplace',
                'description' => 'An exclusive forum for current and aspiring leaders to explore contemporary leadership challenges, emotional intelligence, team management, and organizational culture.',
                'location' => 'Sheraton Hotel, Bulawayo',
                'location_type' => 'physical',
                'start_date' => now()->addDays(60),
                'start_time' => '09:00',
                'end_time' => '16:00',
                'capacity' => 150,
                'amount' => 85,
                'currency' => 'USD',
                'duration_hours' => 7,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Investment & Wealth Creation Summit',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Finance & Investment')->first()->id,
                'short_description' => 'Learn strategies for building and preserving wealth',
                'description' => 'Connect with financial experts to learn about investment opportunities, portfolio management, real estate, and wealth preservation strategies tailored for the African market.',
                'location' => 'Virtual Event',
                'location_type' => 'online',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(35),
                'start_time' => '14:00',
                'end_time' => '18:00',
                'capacity' => 500,
                'amount' => 40,
                'currency' => 'USD',
                'duration_hours' => 4,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Business Networking Night',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Networking Events')->first()->id,
                'short_description' => 'Connect with entrepreneurs and business leaders',
                'description' => 'An evening of structured networking designed to help entrepreneurs, business owners, and professionals make meaningful connections and explore collaboration opportunities.',
                'location' => 'Borrowdale Country Club, Harare',
                'location_type' => 'physical',
                'start_date' => now()->addDays(15),
                'start_time' => '18:00',
                'end_time' => '21:00',
                'capacity' => 100,
                'amount' => 25,
                'currency' => 'USD',
                'duration_hours' => 3,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Annual Entrepreneurship Conference',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Conferences & Summits')->first()->id,
                'short_description' => 'The biggest entrepreneurship event of the year',
                'description' => 'A three-day conference featuring international speakers, workshops, exhibitions, and networking sessions focused on entrepreneurship, innovation, and business growth.',
                'location' => 'Harare International Conference Centre',
                'location_type' => 'hybrid',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(90),
                'start_time' => '08:00',
                'end_time' => '18:00',
                'capacity' => 2000,
                'amount' => 150,
                'currency' => 'USD',
                'duration_hours' => 30,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Women in Business Breakfast',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Business & Entrepreneurship')->first()->id,
                'short_description' => 'Empowering women entrepreneurs through connection and learning',
                'description' => 'An inspiring breakfast event celebrating women in business, featuring successful female entrepreneurs sharing their journeys, challenges, and strategies for success.',
                'location' => 'Meikles Hotel, Harare',
                'location_type' => 'physical',
                'start_date' => now()->addDays(25),
                'start_time' => '07:30',
                'end_time' => '10:00',
                'capacity' => 80,
                'amount' => 30,
                'currency' => 'USD',
                'duration_hours' => 2.5,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'E-Commerce Growth Workshop',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Technology & Innovation')->first()->id,
                'short_description' => 'Scale your online business with proven strategies',
                'description' => 'A practical workshop covering e-commerce platforms, payment integration, logistics, digital marketing for online stores, and customer retention strategies.',
                'location' => 'Virtual Event',
                'location_type' => 'online',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(40),
                'start_time' => '13:00',
                'end_time' => '17:00',
                'capacity' => 300,
                'amount' => 35,
                'currency' => 'USD',
                'duration_hours' => 4,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Sales Mastery Bootcamp',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Marketing & Sales')->first()->id,
                'short_description' => 'Transform your sales approach and close more deals',
                'description' => 'Intensive two-day bootcamp teaching advanced sales techniques, negotiation skills, customer psychology, and pipeline management for professional salespeople.',
                'location' => 'Rainbow Towers, Harare',
                'location_type' => 'physical',
                'start_date' => now()->addDays(50),
                'start_time' => '09:00',
                'end_time' => '17:00',
                'capacity' => 120,
                'amount' => 120,
                'currency' => 'USD',
                'duration_hours' => 16,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'CEO Roundtable Discussion',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Leadership & Management')->first()->id,
                'short_description' => 'Executive-level discussion on business challenges and opportunities',
                'description' => 'An exclusive roundtable for CEOs and senior executives to discuss industry trends, strategic challenges, and share insights in a confidential setting.',
                'location' => 'Private Venue, Harare',
                'location_type' => 'physical',
                'start_date' => now()->addDays(55),
                'start_time' => '15:00',
                'end_time' => '18:00',
                'capacity' => 30,
                'amount' => 200,
                'currency' => 'USD',
                'duration_hours' => 3,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Personal Finance Workshop',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Finance & Investment')->first()->id,
                'short_description' => 'Take control of your financial future',
                'description' => 'Learn budgeting, saving strategies, debt management, and basic investing principles to build a solid financial foundation.',
                'location' => 'Virtual Event',
                'location_type' => 'online',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(22),
                'start_time' => '18:00',
                'end_time' => '20:00',
                'capacity' => 400,
                'amount' => 15,
                'currency' => 'USD',
                'duration_hours' => 2,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Young Entrepreneurs Meetup',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Networking Events')->first()->id,
                'short_description' => 'Connect with the next generation of business leaders',
                'description' => 'A casual meetup for young entrepreneurs under 35 to network, share experiences, and build supportive relationships with peers.',
                'location' => 'Book Cafe, Harare',
                'location_type' => 'physical',
                'start_date' => now()->addDays(18),
                'start_time' => '17:00',
                'end_time' => '20:00',
                'capacity' => 60,
                'amount' => 10,
                'currency' => 'USD',
                'duration_hours' => 3,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'International Trade Summit',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Conferences & Summits')->first()->id,
                'short_description' => 'Explore opportunities in international business',
                'description' => 'A summit focused on export opportunities, international trade regulations, cross-border partnerships, and global market trends.',
                'location' => 'Elephant Hills Resort, Victoria Falls',
                'location_type' => 'hybrid',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(75),
                'start_time' => '08:30',
                'end_time' => '17:30',
                'capacity' => 400,
                'amount' => 180,
                'currency' => 'USD',
                'duration_hours' => 9,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Innovation Pitch Night',
                'type' => 'event',
                'category_id' => $eventCategories->where('name', 'Technology & Innovation')->first()->id,
                'short_description' => 'Watch startups pitch their innovative ideas to investors',
                'description' => 'An exciting evening where selected startups present their business ideas to a panel of investors and industry experts, with networking opportunities for all attendees.',
                'location' => 'Impact Hub Harare',
                'location_type' => 'physical',
                'start_date' => now()->addDays(28),
                'start_time' => '18:00',
                'end_time' => '21:00',
                'capacity' => 150,
                'amount' => 20,
                'currency' => 'USD',
                'duration_hours' => 3,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
        ];

        // Courses Data (15 courses)
        $courses = [
            [
                'title' => 'Complete Business Management Certificate',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Business Management')->first()->id,
                'short_description' => '12-week comprehensive program in business management and strategy',
                'description' => 'This certificate program covers all aspects of business management including strategic planning, operations, finance, marketing, and human resources. Perfect for aspiring managers and entrepreneurs.',
                'location' => 'Hybrid - Online & In-person Sessions',
                'location_type' => 'hybrid',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(21),
                'start_time' => '18:00',
                'end_time' => '21:00',
                'capacity' => 40,
                'amount' => 450,
                'currency' => 'USD',
                'duration_hours' => 144,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Digital Marketing Professional Certification',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Digital Marketing')->first()->id,
                'short_description' => '8-week intensive course in modern digital marketing',
                'description' => 'Master SEO, social media marketing, content marketing, email campaigns, Google Ads, Facebook Ads, and analytics. Includes real-world projects and certification.',
                'location' => 'Virtual Learning Platform',
                'location_type' => 'online',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(14),
                'start_time' => '19:00',
                'end_time' => '21:00',
                'capacity' => 60,
                'amount' => 350,
                'currency' => 'USD',
                'duration_hours' => 64,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Full-Stack Web Development Bootcamp',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Software Development')->first()->id,
                'short_description' => '16-week intensive program to become a professional web developer',
                'description' => 'Learn HTML, CSS, JavaScript, React, Node.js, databases, and deployment. Build real applications and create a professional portfolio. Job placement assistance included.',
                'location' => 'Impact Hub Harare',
                'location_type' => 'physical',
                'start_date' => now()->addDays(30),
                'start_time' => '09:00',
                'end_time' => '17:00',
                'capacity' => 25,
                'amount' => 1200,
                'currency' => 'USD',
                'duration_hours' => 512,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Data Science & Machine Learning',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Data Science & Analytics')->first()->id,
                'short_description' => '10-week program in data analysis and machine learning',
                'description' => 'Learn Python programming, data analysis, visualization, statistics, and machine learning algorithms. Work on real datasets and build predictive models.',
                'location' => 'Virtual Learning Platform',
                'location_type' => 'online',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(35),
                'start_time' => '18:00',
                'end_time' => '21:00',
                'capacity' => 50,
                'amount' => 600,
                'currency' => 'USD',
                'duration_hours' => 120,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Project Management Professional (PMP) Prep',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Project Management')->first()->id,
                'short_description' => '6-week intensive preparation for PMP certification',
                'description' => 'Comprehensive PMP exam preparation covering all knowledge areas, processes, and best practices. Includes practice exams and study materials.',
                'location' => 'Rainbow Towers Training Center',
                'location_type' => 'hybrid',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(28),
                'start_time' => '17:30',
                'end_time' => '20:30',
                'capacity' => 35,
                'amount' => 550,
                'currency' => 'USD',
                'duration_hours' => 54,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Financial Accounting & Bookkeeping',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Financial Management')->first()->id,
                'short_description' => '8-week course in practical accounting and bookkeeping',
                'description' => 'Learn financial accounting principles, bookkeeping practices, financial statements, and accounting software. Suitable for small business owners and aspiring accountants.',
                'location' => 'Virtual Learning Platform',
                'location_type' => 'online',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(25),
                'start_time' => '18:30',
                'end_time' => '20:30',
                'capacity' => 45,
                'amount' => 300,
                'currency' => 'USD',
                'duration_hours' => 64,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Leadership Excellence Program',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Personal Development')->first()->id,
                'short_description' => '6-week program to develop exceptional leadership skills',
                'description' => 'Develop leadership competencies including emotional intelligence, strategic thinking, team building, conflict resolution, and change management.',
                'location' => 'Meikles Hotel Executive Center',
                'location_type' => 'physical',
                'start_date' => now()->addDays(42),
                'start_time' => '14:00',
                'end_time' => '18:00',
                'capacity' => 30,
                'amount' => 650,
                'currency' => 'USD',
                'duration_hours' => 72,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Public Speaking & Presentation Mastery',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Communication Skills')->first()->id,
                'short_description' => '4-week intensive course to become a confident speaker',
                'description' => 'Overcome stage fright, structure compelling presentations, use body language effectively, and engage any audience. Includes live practice sessions with feedback.',
                'location' => 'Impact Hub Harare',
                'location_type' => 'physical',
                'start_date' => now()->addDays(20),
                'start_time' => '17:00',
                'end_time' => '20:00',
                'capacity' => 20,
                'amount' => 280,
                'currency' => 'USD',
                'duration_hours' => 48,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Social Media Marketing Masterclass',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Digital Marketing')->first()->id,
                'short_description' => '5-week deep dive into social media strategy and execution',
                'description' => 'Master Facebook, Instagram, LinkedIn, Twitter, and TikTok marketing. Learn content creation, community management, paid advertising, and analytics.',
                'location' => 'Virtual Learning Platform',
                'location_type' => 'online',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(16),
                'start_time' => '18:00',
                'end_time' => '20:00',
                'capacity' => 70,
                'amount' => 220,
                'currency' => 'USD',
                'duration_hours' => 40,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Python Programming for Beginners',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Software Development')->first()->id,
                'short_description' => '8-week introduction to programming with Python',
                'description' => 'Start your programming journey with Python. Learn fundamentals, data structures, algorithms, and build practical projects. No prior experience required.',
                'location' => 'Virtual Learning Platform',
                'location_type' => 'online',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(23),
                'start_time' => '19:00',
                'end_time' => '21:00',
                'capacity' => 55,
                'amount' => 320,
                'currency' => 'USD',
                'duration_hours' => 64,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Business Analytics & Intelligence',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Data Science & Analytics')->first()->id,
                'short_description' => '7-week course in business data analysis and reporting',
                'description' => 'Learn to analyze business data, create dashboards, perform statistical analysis, and make data-driven decisions using Excel, Power BI, and SQL.',
                'location' => 'Hybrid - Online & In-person',
                'location_type' => 'hybrid',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(33),
                'start_time' => '18:00',
                'end_time' => '21:00',
                'capacity' => 40,
                'amount' => 420,
                'currency' => 'USD',
                'duration_hours' => 84,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Agile & Scrum Certification',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Project Management')->first()->id,
                'short_description' => '3-week intensive Agile and Scrum Master preparation',
                'description' => 'Master Agile methodologies and prepare for Scrum Master certification. Learn sprint planning, daily standups, retrospectives, and agile team management.',
                'location' => 'Virtual Learning Platform',
                'location_type' => 'online',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(19),
                'start_time' => '17:00',
                'end_time' => '20:00',
                'capacity' => 50,
                'amount' => 380,
                'currency' => 'USD',
                'duration_hours' => 36,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Entrepreneurship & Startup Fundamentals',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Business Management')->first()->id,
                'short_description' => '10-week program for aspiring entrepreneurs',
                'description' => 'Learn how to develop a business idea, create a business plan, validate your market, raise funding, and launch your startup. Mentorship included.',
                'location' => 'Impact Hub Harare',
                'location_type' => 'physical',
                'start_date' => now()->addDays(38),
                'start_time' => '18:00',
                'end_time' => '21:00',
                'capacity' => 30,
                'amount' => 480,
                'currency' => 'USD',
                'duration_hours' => 120,
                'is_active' => true,
                'is_featured' => true,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Investment & Portfolio Management',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Financial Management')->first()->id,
                'short_description' => '6-week course on building and managing investment portfolios',
                'description' => 'Learn investment principles, asset allocation, risk management, stock analysis, bonds, mutual funds, and portfolio optimization strategies.',
                'location' => 'Virtual Learning Platform',
                'location_type' => 'online',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(27),
                'start_time' => '19:00',
                'end_time' => '21:00',
                'capacity' => 60,
                'amount' => 390,
                'currency' => 'USD',
                'duration_hours' => 48,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
            [
                'title' => 'Effective Communication & Emotional Intelligence',
                'type' => 'course',
                'category_id' => $courseCategories->where('name', 'Communication Skills')->first()->id,
                'short_description' => '5-week program to enhance interpersonal communication',
                'description' => 'Develop emotional intelligence, active listening, empathy, assertiveness, and conflict resolution skills for professional and personal success.',
                'location' => 'Hybrid - Online & In-person',
                'location_type' => 'hybrid',
                'meeting_link' => 'https://zoom.us/j/example',
                'start_date' => now()->addDays(24),
                'start_time' => '17:30',
                'end_time' => '20:00',
                'capacity' => 35,
                'amount' => 320,
                'currency' => 'USD',
                'duration_hours' => 50,
                'is_active' => true,
                'is_featured' => false,
                'published_at' => now(),
                'created_by' => $adminId,
            ],
        ];

        // Create events and attach instructors
        foreach ($events as $eventData) {
            $eventData['slug'] = Str::slug($eventData['title']);
            $event = Event::create($eventData);

            // Attach 1-3 random instructors to each event
            $randomInstructors = $instructors->random(rand(1, 3))->pluck('id');
            $event->instructors()->attach($randomInstructors);
        }

        // Create courses and attach instructors
        foreach ($courses as $courseData) {
            $courseData['slug'] = Str::slug($courseData['title']);
            $course = Event::create($courseData);

            // Attach 1-2 random instructors to each course
            $randomInstructors = $instructors->random(rand(1, 2))->pluck('id');
            $course->instructors()->attach($randomInstructors);
        }
    }
}
